spring.application.name=DDocker
server.port=${APP_PORT:8081}

# O Spring busca a variável DB_PORT_EXTERNAL, se não achar, usa 5050
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT_EXTERNAL}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true