services:
  db:
    ports:
      - "${DB_PORT_EXTERNAL}:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-desafio
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db