services:
  db:
    image: postgres:15-alpine
    container_name: postgres-desafio
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=senha_forte
      - POSTGRES_DB=desafio_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: